"""
Pentagonal numbers are generated by the formula, Pn = n * (3 * n - 1) / 2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
"""
from itertools import count
from euler import pentagonal, Pentagonals

def f():
    for n in count(1):
        pn = pentagonal(n)
        lower_pentagonals = [pentagonal(i) for i in range(1, n)]
        for p in lower_pentagonals:
            if pn - p in Pentagonals and pn + p in Pentagonals:
                return pn - p

result = f()
